name: edusport_manager
description: "EduSport Manager — إدارة ومتابعة التلاميذ (Flutter + Supabase)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Backend
  supabase_flutter: ^2.5.6

  # State management
  provider: ^6.1.2

  # Charts for statistics
  fl_chart: ^0.68.0

  # Routing
  go_router: ^14.2.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3

  # Fonts / RTL friendly Arabic font
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
